
- name: install apache and firewall
  hosts: node1, node2, node3
  become: true

  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running fine
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http services
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
